CREATE DATABASE DATA;

USE DATA;

SELECT * FROM SALES_D;

SELECT * FROM CUSTOMERS_DATA;
 
SELECT * FROM REGIONS;

SELECT * FROM PRODUCTS_DATA;

ALTER TABLE CUSTOMERS_DATA MODIFY COLUMN JOIN_DATE DATE;

ALTER TABLE CUSTOMERS_DATA ADD COLUMN NEW_DATE DATE;

UPDATE CUSTOMERS_DATA
SET NEW_DATE = STR_TO_DATE(JOIN_DATE , "%d-%m-%Y");

ALTER TABLE CUSTOMERS_DATA DROP COLUMN JOIN_DATE;

ALTER TABLE SALES_D ADD COLUMN NEW_SALE_DATE DATE;

UPDATE SALES_D
SET NEW_SALE_DATE = STR_TO_DATE(SALE_DATE , "%d-%m-%Y");

ALTER TABLE SALES_D DROP COLUMN SALE_DATE;

ALTER TABLE CUSTOMERS_DATA RENAME COLUMN NEW_DATE TO JOIN_DATE;

ALTER TABLE SALES_D RENAME COLUMN NEW_SALE_DATE TO SALE_DATE;



#1---- Total Sales Revenue:-

SELECT SUM(TOTAL_AMOUNT) FROM SALES_D;


#2---- Top 10 Best-Selling Products:-

SELECT P.PRODUCT_NAME , SUM(TOTAL_AMOUNT) AS TOTAL_SALES , SUM(S.QUANTITY) AS TOTAL_QUANTITY  FROM SALES_D AS S 
JOIN PRODUCTS_DATA AS P
ON P.PRODUCT_ID = S.PRODUCT_ID
GROUP BY P.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC
LIMIT 10;


#3----- Monthly Sales Trend:-

SELECT YEAR(SALE_DATE) AS YEAR , MONTH(SALE_DATE) AS MONTH,MONTHNAME(SALE_DATE),SUM(TOTAL_AMOUNT)AS SALES  FROM SALES_D
GROUP BY YEAR(SALE_DATE),MONTH(SALE_DATE),MONTHNAME(SALE_DATE)
ORDER BY YEAR,MONTH;

SELECT 
    DATE_FORMAT(sale_date, '%Y-%m') AS year,
    SUM(total_amount) AS monthly_sales
FROM sales_d
GROUP BY year
ORDER BY year;

#4----- Region-wise Revenue:-

SELECT C.LOCATION, SUM(TOTAL_AMOUNT) AS REVENUE FROM SALES_D AS S
JOIN CUSTOMERS_DATA AS C
ON C.CUSTOMER_ID = S.CUSTOMER_ID
GROUP BY C.LOCATION
ORDER BY REVENUE DESC;


#5----- Top 10 Customers by Lifetime Value:-

SELECT C.CUSTOMER_ID , C.NAME , C.LOCATION , SUM(TOTAL_AMOUNT) AS LIFETIME_VALUE FROM SALES_D AS S
JOIN CUSTOMERS_DATA AS C
ON C.CUSTOMER_ID = S.CUSTOMER_ID
GROUP BY CUSTOMER_ID , C.NAME , C.LOCATION 
ORDER BY LIFETIME_VALUE DESC
LIMIT 10;


#6----- Category-wise Sales Distribution:-

SELECT CATEGORY , SUM(TOTAL_AMOUNT) AS CATEGORY_SALES, 
RANK() OVER(ORDER BY SUM(TOTAL_AMOUNT) DESC) AS SALES_RANK FROM SALES_D AS S
JOIN PRODUCTS_DATA AS P
ON S.PRODUCT_ID = P.PRODUCT_ID
GROUP BY CATEGORY;


#7----- Average Order Value (AOV):-

SELECT AVG(TOTAL_AMOUNT) AS AOV
 FROM SALES_D;
 

#8---- Repeat Customers (who bought more than once):-

SELECT C.CUSTOMER_ID , NAME , COUNT(DISTINCT SALE_ID) AS TOTAL_ORDERS FROM SALES_D AS S
JOIN CUSTOMERS_DATA AS C
ON C.CUSTOMER_ID = S.CUSTOMER_ID
GROUP BY C.CUSTOMER_ID , NAME
ORDER BY TOTAL_ORDERS  DESC
LIMIT 1;

SELECT c.customer_id, c.name, COUNT(DISTINCT s.sale_id) AS total_orders
FROM sales_D AS S
JOIN customers_DATA c ON s.customer_id = c.customer_id
GROUP BY c.customer_id, c.name
HAVING COUNT(DISTINCT s.sale_id) > 1
ORDER BY total_orders DESC;


#9-----Daily Sales Trend (last 30 days):-

SELECT DATE(SALE_DATE)AS DAY , SUM(TOTAL_AMOUNT) AS SALES_TREND FROM SALES_D
GROUP BY DATE(SALE_DATE)
ORDER BY DAY ASC;


#10-----YEARLY SALES TREND:-
SELECT YEAR(SALE_DATE)AS YEAR , SUM(TOTAL_AMOUNT) AS SALES_TREND FROM SALES_D
GROUP BY YEAR(SALE_DATE)
ORDER BY YEAR;

SELECT DATE(SALE_DATE) AS DAY , SUM(TOTAL_AMOUNT) FROM SALES_D
WHERE SALE_DATE >= 2022-03-02
GROUP BY DATE(SALE_DATE)
ORDER BY DATE(SALE_DATE);












